/**
 * Vehicle Specifications & Catalog Registry
 * Balanced thrust-to-weight ratios so starter drones and planes can effortlessly lift any cargo.
 */

import type { VehicleId, VehicleSpecs } from './types.js';

export const VEHICLE_CATALOG: Record<VehicleId, VehicleSpecs> = {
  sparrow_tier1: {
    id: 'sparrow_tier1',
    name: 'The Sparrow',
    vehicleClass: 'drone',
    tier: 1,
    price: 0, // Starter vehicle
    description: 'A humble wooden garage quadcopter. A bit shaky in mountain winds, but eager to please!',
    massKg: 1.4,
    maxThrustN: 82.0, // High thrust-to-weight ratio to lift parcels with ease!
    maxAirspeedKmh: 52,
    stallSpeedKmh: 0,
    glideRatio: 0,
    torqueRollPitch: 1.6,
    torqueYaw: 2.2,
    linearDrag: [0.7, 0.7, 0.7],
    angularDrag: [2.5, 2.5, 2.5],
    baseGyroAssist: 0.25,
    batteryCapacitySeconds: 180,
    maxPayloadKg: 4.5,
    slingLengthM: 1.5,
    magneticRadiusM: 2.2,
  },
  swallow_tier2: {
    id: 'swallow_tier2',
    name: 'Alpine Swallow',
    vehicleClass: 'drone',
    tier: 2,
    price: 450,
    description: 'Sleek carbon-fiber delivery quad with balanced brushless motors and responsive handling.',
    massKg: 2.0,
    maxThrustN: 135.0,
    maxAirspeedKmh: 75,
    stallSpeedKmh: 0,
    glideRatio: 0,
    torqueRollPitch: 2.1,
    torqueYaw: 2.6,
    linearDrag: [0.8, 0.8, 0.8],
    angularDrag: [3.0, 3.0, 3.0],
    baseGyroAssist: 0.45,
    batteryCapacitySeconds: 240,
    maxPayloadKg: 8.0,
    slingLengthM: 1.7,
    magneticRadiusM: 2.6,
  },
  titan_tier3: {
    id: 'titan_tier3',
    name: 'Matterhorn Titan',
    vehicleClass: 'drone',
    tier: 3,
    price: 1100,
    description: 'Heavy-duty 6-rotor industrial hauler capable of lifting giant cheese wheels and tool crates.',
    massKg: 3.6,
    maxThrustN: 260.0,
    maxAirspeedKmh: 65,
    stallSpeedKmh: 0,
    glideRatio: 0,
    torqueRollPitch: 1.8,
    torqueYaw: 2.4,
    linearDrag: [1.2, 1.2, 1.2],
    angularDrag: [3.5, 3.5, 3.5],
    baseGyroAssist: 0.6,
    batteryCapacitySeconds: 320,
    maxPayloadKg: 18.0,
    slingLengthM: 2.2,
    magneticRadiusM: 3.2,
  },
  zephyr_tier1: {
    id: 'zephyr_tier1',
    name: 'Zephyr Glider',
    vehicleClass: 'plane',
    tier: 1,
    price: 250,
    description: 'Ultra-lightweight foam RC glider with long graceful wings. Excels at soaring through thermal updrafts.',
    massKg: 1.2,
    maxThrustN: 48.0,
    maxAirspeedKmh: 95,
    stallSpeedKmh: 28,
    glideRatio: 14.0,
    torqueRollPitch: 1.8,
    torqueYaw: 1.6,
    linearDrag: [0.25, 0.25, 0.25],
    angularDrag: [2.5, 2.5, 2.5],
    baseGyroAssist: 0.3,
    batteryCapacitySeconds: 340,
    maxPayloadKg: 3.5,
    slingLengthM: 1.6,
    magneticRadiusM: 2.4,
  },
  aeolus_tier2: {
    id: 'aeolus_tier2',
    name: 'Aeolus Express',
    vehicleClass: 'plane',
    tier: 2,
    price: 750,
    description: 'Twin-engine vintage biplane inspired by Swiss alpine postal couriers. High airspeed and lift capacity.',
    massKg: 2.8,
    maxThrustN: 110.0,
    maxAirspeedKmh: 130,
    stallSpeedKmh: 36,
    glideRatio: 9.5,
    torqueRollPitch: 2.2,
    torqueYaw: 2.0,
    linearDrag: [0.4, 0.4, 0.4],
    angularDrag: [3.0, 3.0, 3.0],
    baseGyroAssist: 0.45,
    batteryCapacitySeconds: 290,
    maxPayloadKg: 10.0,
    slingLengthM: 1.9,
    magneticRadiusM: 2.8,
  },
};
